name: CI

on: [push, pull_request]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "~1.18"

      - name: Install utilities
        run: |
          go install golang.org/x/lint/golint@latest
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          # display Go environment for reference
          go env

      - name: Build
        run: |
          go build -v ./...

      - name: Check
        run: |
          go vet ./...
          golint ./...
          staticcheck ./...
          goimports -w .
          /usr/bin/git diff --exit-code

      - name: Test
        run: |
          go test -v ./...
